DROP TABLE "BUSINESS_MEMBER";
DROP TABLE "COMPANY";
DROP TABLE "FILE";
DROP TABLE "REVIEW";
DROP TABLE "USER_MEMBER";
DROP TABLE "USER_QnA";
DROP TABLE "BUSINESS_QnA";
DROP TABLE "BOOKING_MENU";
DROP TABLE "USER_BOOKMARK";
DROP TABLE "NOTICE";
DROP TABLE "CLAUSE";
DROP TABLE "ADMIN_QnA";
DROP TABLE "ADMIN";
DROP TABLE "MENU";
DROP TABLE "BOOKING";
DROP TABLE "CLAUSE_AGREE";


CREATE TABLE "BUSINESS_MEMBER" (
   "BU_NO"   NUMBER      NOT NULL,
   "BU_NUMBER"   VARCHAR2(20)      NOT NULL,
   "BU_ID"   VARCHAR2(20)      NOT NULL,
   "BU_PWD"   VARCHAR2(40)      NOT NULL,
   "BU_NAME"   VARCHAR2(20)      NOT NULL,
   "BU_BIRTH"   VARCHAR2(20)      NOT NULL,
   "BU_GENDER"   VARCHAR2(1)      NOT NULL,
   "BU_EMAIL"   VARCHAR2(20)      NOT NULL,
   "BU_TEL"   VARCHAR2(20)      NOT NULL,
   "BU_USEYN"   VARCHAR2(1)   DEFAULT 'Y'   NOT NULL,
   "BU_WRITE_DATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NULL,
   "BU_UPDATE_DATE"   TIMESTAMP      NULL,
   "BU_OUT_DATE"   TIMESTAMP      NULL,
   "FL_GNO"   VARCHAR2(4000)      NULL
);

COMMENT ON COLUMN "BUSINESS_MEMBER"."BU_GENDER" IS 'M/F';

COMMENT ON COLUMN "BUSINESS_MEMBER"."BU_USEYN" IS 'Y/N';

CREATE TABLE "COMPANY" (
   "CP_NO"   NUMBER      NOT NULL,
   "BU_NO"   NUMBER      NOT NULL,
   "CP_CATEGORY"   VARCHAR2(20)      NOT NULL,
   "CP_NAME"   VARCHAR2(20)      NOT NULL,
   "CP_EXPLAIN"   VARCHAR2(4000)      NULL,
   "CP_CLASSIFY"   VARCHAR2(1)      NOT NULL,
   "CP_OPEN_DATE"   TIMESTAMP      NULL,
   "CP_CLOSE_DATE"   TIMESTAMP      NULL,
   "CP_OPEN_TIME"   VARCHAR2(100)      NULL,
   "CP_CLOSE_TIME"   VARCHAR2(100)      NULL,
   "CP_TERM"   VARCHAR2(100)      NULL,
   "CP_POSTNUM"   VARCHAR2(20)      NOT NULL,
   "CP_ADDRESS"   VARCHAR2(200)      NOT NULL,
   "CP_DTADDRESS"   VARCHAR2(1000)      NOT NULL,
   "CP_WRITE_DATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NULL,
   "CP_UPDATE_DATE"   TIMESTAMP      NULL,
   "FL_GNO"   VARCHAR2(4000)      NULL
);

COMMENT ON COLUMN "COMPANY"."CP_CATEGORY" IS '카페/미용실/호텔';

COMMENT ON COLUMN "COMPANY"."CP_CLASSIFY" IS '항상 : A / 특정기간 : B';

CREATE TABLE "MENU" (
   "MENU_NO"   NUMBER      NOT NULL,
   "CP_NO"   NUMBER      NOT NULL,
   "MENU_NAME"   VARCHAR2(100)      NOT NULL,
   "MENU_PRICE"   NUMBER      NOT NULL,
   "MENU_EXPLAIN"   VARCHAR2(1000)      NULL,
   "MENU_USEYN"   VARCHAR2(1)   DEFAULT 'Y'   NULL,
   "MENU_WRITE_DATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NULL,
   "MENU_UPDATE_DATE"   TIMESTAMP      NULL,
   "FL_GNO"   VARCHAR2(4000)      NULL
);

COMMENT ON COLUMN "MENU"."MENU_USEYN" IS 'Y/N';

CREATE TABLE "FILE" (
   "FL_GNO"   VARCHAR2(4000)      NOT NULL,
   "FL_NAME"   VARCHAR2(4000)      NOT NULL,
   "FL_RENAME"   VARCHAR2(4000)      NULL,
   "FL_SRC"   VARCHAR2(4000)      NOT NULL,
   "FILE_WRITE_DATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NULL
);

CREATE TABLE "REVIEW" (
   "RV_NO"   NUMBER      NOT NULL,
   "UM_ID"   VARCHAR2(20)      NOT NULL,
   "RV_CNO"   NUMBER      NOT NULL,
   "RV_SCORE"   NUMBER      NOT NULL,
   "RV_CONTENT"   VARCHAR2(4000)      NOT NULL,
   "RV_WRITE_DATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NOT NULL,
   "RV_MODIFY_DATE"   TIMESTAMP      NULL,
   "FL_GNO"   VARCHAR2(4000)      NULL
);

COMMENT ON COLUMN "REVIEW"."RV_WRITE_DATE" IS 'YYYY-MM-DD';

CREATE TABLE "USER_MEMBER" (
   "UM_ID"   VARCHAR2(20)      NOT NULL,
   "UM_PWD"   VARCHAR2(40)      NOT NULL,
   "UM_NAME"   VARCHAR2(20)      NOT NULL,
   "UM_GENDER"   VARCHAR2(1)      NOT NULL,
   "UM_BIRTH"   VARCHAR2(20)      NOT NULL,
   "UM_TEL"   VARCHAR2(20)      NOT NULL,
   "UM_POSTCODE"   VARCHAR2(20)      NOT NULL,
   "UM_ADDRESS"   VARCHAR2(100)      NOT NULL,
   "UM_DETAIL_ADDRESS"   VARCHAR2(100)      NOT NULL,
   "UM_EMAIL"   VARCHAR2(40)      NOT NULL,
   "UM_POINT"   NUMBER(10,1)   DEFAULT 0   NOT NULL,
   "UM_USEYN"   VARCHAR2(1)   DEFAULT 'Y'   NOT NULL,
   "UM_WRITE_DATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NULL,
   "UM_UPDATE_DATE"   TIMESTAMP      NULL,
   "UM_OUT_DATE"   TIMESTAMP      NULL
);

COMMENT ON COLUMN "USER_MEMBER"."UM_GENDER" IS 'M/F';

COMMENT ON COLUMN "USER_MEMBER"."UM_BIRTH" IS 'xxxx-xx-xx';

COMMENT ON COLUMN "USER_MEMBER"."UM_TEL" IS 'xxx-xxxx-xxxx';

COMMENT ON COLUMN "USER_MEMBER"."UM_ADDRESS" IS '주소 API';

COMMENT ON COLUMN "USER_MEMBER"."UM_USEYN" IS 'Y/N';

CREATE TABLE "BOOKING" (
   "BK_NO"   NUMBER      NOT NULL,
   "CP_NO"   NUMBER      NOT NULL,
   "UM_ID"   VARCHAR2(20)      NOT NULL,
   "BK_NAME"   VARCHAR2(20)      NOT NULL,
   "BK_PHONE"   VARCHAR2(20)      NOT NULL,
   "BK_REQUIRE"   VARCHAR2(1000)      NULL,
   "BK_DATE"   VARCHAR2(40)      NOT NULL,
   "BK_CDATE"   TIMESTAMP      NULL,
   "BK_TIME"   VARCHAR2(40)      NOT NULL,
   "BK_STATUS"   VARCHAR2(1)      NOT NULL,
   "BK_PAY"   VARCHAR2(1)      NOT NULL,
   "BK_WRITE_DATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NULL,
   "BK_UPDATE_DATE"   TIMESTAMP      NULL
);

COMMENT ON COLUMN "BOOKING"."BK_STATUS" IS '대기 H/ 예약 R / 취소 : C';

COMMENT ON COLUMN "BOOKING"."BK_PAY" IS '결제 API';

CREATE TABLE "USER_QnA" (
   "UQ_NO"   NUMBER      NOT NULL,
   "BU_NO"   NUMBER      NOT NULL,
   "UQ_TITLE"   VARCHAR2(20)      NOT NULL,
   "UQ_CONTENT"   VARCHAR2(4000)      NOT NULL,
   "UQ_ANSWER"   VARCHAR2(4000)      NULL,
   "UQ_WRITE_DATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NULL,
   "UQ_UPDATE_DATE"   TIMESTAMP      NULL
);

CREATE TABLE "BUSINESS_QnA" (
   "BQ_NO"   NUMBER      NOT NULL,
   "BQ_TITLE"   VARCHAR2(20)      NOT NULL,
   "BQ_CONTENT"   VARCHAR2(4000)      NOT NULL,
   "BQ_ANSWER"   VARCHAR2(4000)      NULL,
   "BQ_WRITE_DATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NULL,
   "BQ_UPDATE_DATE"   TIMESTAMP      NULL
);

CREATE TABLE "BOOKING_MENU" (
   "BKM_NO"   NUMBER      NOT NULL,
   "BK_NO"   NUMBER      NOT NULL,
   "MENU_NO"   NUMBER      NULL,
   "BKM_WRITE_DATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NULL,
   "BKM_UPDATE_DATE"   TIMESTAMP      NULL
);

CREATE TABLE "USER_BOOKMARK" (
   "UB_NO"   NUMBER      NOT NULL,
   "UM_ID"   VARCHAR2(20)      NOT NULL,
   "CP_NO"   NUMBER      NOT NULL,
   "UB_WRITEDATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NULL
);

CREATE TABLE "ADMIN" (
   "AD_NO"   NUMBER      NOT NULL,
   "AD_ID"   VARCHAR2(20)      NOT NULL,
   "AD_PW"   VARCHAR2(40)      NOT NULL
);

CREATE TABLE "NOTICE" (
   "NT_NO"   NUMBER      NOT NULL,
   "NT_TITLE"   VARCHAR2(300)      NOT NULL,
   "NT_CONTENT"   VARCHAR2(4000)      NULL,
   "NT_WRITE_DATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NOT NULL,
   "NT_COUNT"   NUMBER   DEFAULT 0   NOT NULL,
   "FL_GNO"   VARCHAR2(4000)      NULL
);

CREATE TABLE "CLAUSE" (
   "CU_CODE"   NUMBER      NOT NULL,
   "CU_NAME"   VARCHAR2(20)      NOT NULL,
   "CU_CONTENT"   VARCHAR2(200)      NOT NULL,
   "CU_REQURIRED"   VARCHAR2(1)      NOT NULL
);

COMMENT ON COLUMN "CLAUSE"."CU_CODE" IS '이용약관 01/개인정보수집 및 이용 동의 02/위치정보서비스 동의03';

COMMENT ON COLUMN "CLAUSE"."CU_NAME" IS '이용약관동의/개인정보 수집 및 이용 동의/위치정보서비스 동의';

COMMENT ON COLUMN "CLAUSE"."CU_REQURIRED" IS 'Y/N';

CREATE TABLE "ADMIN_QnA" (
   "AQ_NO"   NUMBER      NOT NULL,
   "AD_NO"   NUMBER      NOT NULL,
   "AQ_TITLE"   VARCHAR2(20)      NOT NULL,
   "AQ_CONTENT"   VARCHAR2(4000)      NOT NULL,
   "AQ_ANSWER"   VARCHAR2(4000)      NULL,
   "AQ_WRITE_DATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NULL,
   "AQ_UPDATE_DATE"   TIMESTAMP      NULL
);

CREATE TABLE "CLAUSE_AGREE" (
   "CU_CODE"   NUMBER      NOT NULL,
   "UM_ID"   VARCHAR2(20)      NOT NULL,
   "CU_AGREE"   VARCHAR2(1)      NOT NULL,
   "CU_DATE"   TIMESTAMP   DEFAULT SYSTIMESTAMP   NULL
);

COMMENT ON COLUMN "CLAUSE_AGREE"."CU_CODE" IS '이용약관 01/개인정보수집 및 이용 동의 02/위치정보서비스 동의03';

COMMENT ON COLUMN "CLAUSE_AGREE"."CU_AGREE" IS 'Y/N';

COMMENT ON COLUMN "CLAUSE_AGREE"."CU_DATE" IS 'YYYY-MM-DD';

ALTER TABLE "BUSINESS_MEMBER" ADD CONSTRAINT "PK_BUSINESS_MEMBER" PRIMARY KEY (
   "BU_NO"
);

ALTER TABLE "COMPANY" ADD CONSTRAINT "PK_COMPANY" PRIMARY KEY (
   "CP_NO"
);

ALTER TABLE "MENU" ADD CONSTRAINT "PK_MENU" PRIMARY KEY (
   "MENU_NO"
);

ALTER TABLE "FILE" ADD CONSTRAINT "PK_FILE" PRIMARY KEY (
   "FL_GNO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
   "RV_NO"
);

ALTER TABLE "USER_MEMBER" ADD CONSTRAINT "PK_USER_MEMBER" PRIMARY KEY (
   "UM_ID"
);

ALTER TABLE "BOOKING" ADD CONSTRAINT "PK_BOOKING" PRIMARY KEY (
   "BK_NO"
);

ALTER TABLE "USER_QnA" ADD CONSTRAINT "PK_USER_QNA" PRIMARY KEY (
   "UQ_NO"
);

ALTER TABLE "BUSINESS_QnA" ADD CONSTRAINT "PK_BUSINESS_QNA" PRIMARY KEY (
   "BQ_NO"
);

ALTER TABLE "BOOKING_MENU" ADD CONSTRAINT "PK_BOOKING_MENU" PRIMARY KEY (
   "BKM_NO"
);

ALTER TABLE "USER_BOOKMARK" ADD CONSTRAINT "PK_USER_BOOKMARK" PRIMARY KEY (
   "UB_NO"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
   "AD_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
   "NT_NO"
);

ALTER TABLE "ADMIN_QnA" ADD CONSTRAINT "PK_ADMIN_QNA" PRIMARY KEY (
   "AQ_NO"
);

ALTER TABLE "CLAUSE_AGREE" ADD CONSTRAINT "PK_CLAUSE_AGREE" PRIMARY KEY (
   "CU_CODE"
);

ALTER TABLE "BUSINESS_MEMBER" ADD CONSTRAINT "FK_FILE_TO_B_MEMBER_1" FOREIGN KEY (
   "FL_GNO"
)
REFERENCES "FILE" (
   "FL_GNO"
);

ALTER TABLE "COMPANY" ADD CONSTRAINT "FK_B_MEMBER_TO_COMPANY_1" FOREIGN KEY (
   "BU_NO"
)
REFERENCES "BUSINESS_MEMBER" (
   "BU_NO"
);

ALTER TABLE "COMPANY" ADD CONSTRAINT "FK_FILE_TO_COMPANY_1" FOREIGN KEY (
   "FL_GNO"
)
REFERENCES "FILE" (
   "FL_GNO"
);

ALTER TABLE "MENU" ADD CONSTRAINT "FK_COMPANY_TO_MENU_1" FOREIGN KEY (
   "CP_NO"
)
REFERENCES "COMPANY" (
   "CP_NO"
);

ALTER TABLE "MENU" ADD CONSTRAINT "FK_FILE_TO_MENU_1" FOREIGN KEY (
   "FL_GNO"
)
REFERENCES "FILE" (
   "FL_GNO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_U_MEMBER_TO_REVIEW_1" FOREIGN KEY (
   "UM_ID"
)
REFERENCES "USER_MEMBER" (
   "UM_ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_FILE_TO_REVIEW_1" FOREIGN KEY (
   "FL_GNO"
)
REFERENCES "FILE" (
   "FL_GNO"
);

ALTER TABLE "BOOKING" ADD CONSTRAINT "FK_COMPANY_TO_BOOKING_1" FOREIGN KEY (
   "CP_NO"
)
REFERENCES "COMPANY" (
   "CP_NO"
);

ALTER TABLE "BOOKING" ADD CONSTRAINT "FK_U_MEMBER_TO_BOOKING_1" FOREIGN KEY (
   "UM_ID"
)
REFERENCES "USER_MEMBER" (
   "UM_ID"
);

ALTER TABLE "USER_QnA" ADD CONSTRAINT "FK_B_MEMBER_TO_U_QnA_1" FOREIGN KEY (
   "BU_NO"
)
REFERENCES "BUSINESS_MEMBER" (
   "BU_NO"
);

ALTER TABLE "BOOKING_MENU" ADD CONSTRAINT "FK_BOOKING_TO_B_MENU_1" FOREIGN KEY (
   "BK_NO"
)
REFERENCES "BOOKING" (
   "BK_NO"
);

ALTER TABLE "BOOKING_MENU" ADD CONSTRAINT "FK_MENU_TO_B_MENU_1" FOREIGN KEY (
   "MENU_NO"
)
REFERENCES "MENU" (
   "MENU_NO"
);

ALTER TABLE "USER_BOOKMARK" ADD CONSTRAINT "FK_U_MEMBER_TO_U_BOOKMARK_1" FOREIGN KEY (
   "UM_ID"
)
REFERENCES "USER_MEMBER" (
   "UM_ID"
);

ALTER TABLE "USER_BOOKMARK" ADD CONSTRAINT "FK_COMPANY_TO_U_BOOKMARK_1" FOREIGN KEY (
   "CP_NO"
)
REFERENCES "COMPANY" (
   "CP_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_FILE_TO_NOTICE_1" FOREIGN KEY (
   "FL_GNO"
)
REFERENCES "FILE" (
   "FL_GNO"
);

ALTER TABLE "CLAUSE" ADD CONSTRAINT "FK_C_AGREE_TO_CLAUSE_1" FOREIGN KEY (
   "CU_CODE"
)
REFERENCES "CLAUSE_AGREE" (
   "CU_CODE"
);

ALTER TABLE "ADMIN_QnA" ADD CONSTRAINT "FK_ADMIN_TO_A_QnA_1" FOREIGN KEY (
   "AD_NO"
)
REFERENCES "ADMIN" (
   "AD_NO"
);

ALTER TABLE "CLAUSE_AGREE" ADD CONSTRAINT "FK_U_MEMBER_TO_C_AGREE_1" FOREIGN KEY (
   "UM_ID"
)
REFERENCES "USER_MEMBER" (
   "UM_ID"
);
